// questions-basic.js — Questions 1–25 (Basic)
const basicQuestions = [
  {
    id: 1,
    category: "Basic",
    question: "What is PHP?",
    shortAnswer: "PHP ek server-side scripting language hai jo mainly dynamic web pages banane ke liye use hoti hai. Ye HTML ke andar embed ho sakti hai.",
    explanation: "Simple words me samjho: PHP (Hypertext Preprocessor) ek open-source language hai jo server par run hoti hai, browser par nahi. Jab user koi .php page request karta hai, server PHP code ko execute karta hai aur result ko plain HTML me convert karke browser ko bhejta hai. Isliye user ko kabhi actual PHP code nahi dikhta, sirf final output dikhta hai. PHP database (jaise MySQL) ke saath easily connect ho jati hai, isliye ye web development me bahut popular hai.",
    example: "Jab aap koi login form submit karte ho, PHP us data ko server par process karta hai, database me check karta hai, aur result (success/fail) HTML ke form me wapas bhejta hai.",
    code: `<?php\n$name = "Krishna";\necho "Hello, " . $name . "!";\n?>`,
    output: "Hello, Krishna!",
    mistakes: "Beginners aksar sochte hain PHP client-side language hai (jaise JavaScript), lekin ye purely server-side chalti hai — browser me PHP code kabhi visible nahi hota.",
    interviewDefinition: "PHP is a widely-used, open-source, server-side scripting language designed primarily for web development that can be embedded directly into HTML."
  },
  {
    id: 2,
    category: "Basic",
    question: "What are the features of PHP?",
    shortAnswer: "PHP open-source, easy to learn, platform-independent, database-friendly, aur fast execution ke liye jaana jata hai.",
    explanation: "PHP ki sabse badi feature ye hai ki ye free aur open-source hai, isliye koi bhi ise use kar sakta hai bina licensing cost ke. Ye cross-platform hai — Windows, Linux, macOS sab par chalta hai. PHP ka syntax C aur Java jaisa hai, isliye seekhna aasan hai. Ye almost sabhi major databases (MySQL, PostgreSQL, SQLite) ke saath kaam karta hai aur ek bahut bada community/support ecosystem hai (Laravel, Symfony jaise frameworks ke saath).",
    example: "Facebook shuru me PHP par hi bana tha, aur aaj bhi WordPress jaisa CMS jo lakhon websites power karta hai, PHP me likha gaya hai.",
    code: `<?php\n// Cross-platform: same code, works everywhere\nphpinfo();\n?>`,
    output: "PHP Version, Configuration, and Server details table",
    mistakes: "Log ye bhool jate hain ki PHP sirf web development ke liye nahi, CLI scripts aur background jobs ke liye bhi use hota hai.",
    interviewDefinition: "PHP's key features include being open-source, cross-platform, easy to learn, tightly integrated with databases, and backed by a mature ecosystem of frameworks and community support."
  },
  {
    id: 3,
    category: "Basic",
    question: "What is the difference between PHP and HTML?",
    shortAnswer: "HTML ek markup language hai jo static structure banati hai, jabki PHP server-side execute hoti hai aur dynamic content generate karti hai.",
    explanation: "HTML sirf structure aur presentation define karta hai — browser directly HTML ko parse karke render kar deta hai, koi processing nahi hoti. PHP iske bilkul opposite server par execute hota hai; ye logic run karta hai, database se data laata hai, aur phir dynamically HTML generate karta hai jo browser ko bheja jata hai. Yani HTML 'kya dikhna hai' batata hai, PHP 'kaise aur kya data ke saath dikhna hai' decide karta hai.",
    example: "Ek static 'About Us' page HTML me likha ja sakta hai, lekin ek user ka personalized dashboard (jisme uska naam, orders, etc. dikhte hain) PHP se dynamically generate hota hai.",
    code: `<!-- HTML -->\n<h1>Welcome</h1>\n\n<?php\n// PHP\n$user = "Krishna";\necho "<h1>Welcome, $user</h1>";\n?>`,
    output: "Welcome, Krishna",
    mistakes: "Beginners PHP ko 'HTML ka upgrade' samajh lete hain, jabki dono alag purpose serve karte hain — ek presentation ke liye, dusra logic ke liye.",
    interviewDefinition: "HTML is a static markup language for structuring content, while PHP is a server-side scripting language that processes logic and dynamically generates HTML output."
  },
  {
    id: 4,
    category: "Basic",
    question: "What is a variable in PHP?",
    shortAnswer: "Variable ek container hai jo data store karta hai. PHP me variable `$` sign se start hota hai.",
    explanation: "PHP loosely-typed language hai, matlab variable declare karte waqt data type specify karne ki zaroorat nahi hoti — PHP khud value dekh kar type decide kar leta hai (dynamic typing). Variable naam letter ya underscore se start hona chahiye, number se nahi. Variables case-sensitive hote hain, matlab `$name` aur `$Name` do alag variables mane jayenge.",
    example: "Ek shopping cart me `$total_price` variable rakh sakte hain jo cart me items add hone par change hota rahega.",
    code: `<?php\n$name = "Krishna";\n$age = 25;\n$isDeveloper = true;\necho "$name is $age years old.";\n?>`,
    output: "Krishna is 25 years old.",
    mistakes: "Variable naam number se start karna (`$1name`) invalid hai — ye ek common syntax error hai jo beginners karte hain.",
    interviewDefinition: "A variable in PHP is a symbol, prefixed with a dollar sign, used to store data values that can change during script execution, without requiring explicit type declaration."
  },
  {
    id: 5,
    category: "Basic",
    question: "What are PHP data types?",
    shortAnswer: "PHP me main data types hain: String, Integer, Float, Boolean, Array, Object, NULL, aur Resource.",
    explanation: "PHP ek dynamically-typed language hai, isliye variable ka type runtime par decide hota hai based on assigned value. Scalar types (single value) hain: int, float, string, bool. Compound types (multiple values) hain: array aur object. NULL ek special type hai jo 'no value' represent karta hai. Resource type external resources (jaise file handles, database connections) ko refer karta hai. `gettype()` function se kisi variable ka type check kiya ja sakta hai.",
    example: "Ek user registration form me name (string), age (int), height (float), aur isSubscribed (bool) jaise alag-alag data types use honge.",
    code: `<?php\n$str = "Hello";\n$int = 42;\n$float = 3.14;\n$bool = true;\nvar_dump($str, $int, $float, $bool);\n?>`,
    output: 'string(5) "Hello"\nint(42)\nfloat(3.14)\nbool(true)',
    mistakes: "Beginners `\"42\"` (string) aur `42` (integer) ko same samajhte hain, jo `==` comparison me sahi lag sakta hai lekin `===` me fail ho jata hai.",
    interviewDefinition: "PHP supports several data types including scalar types (integer, float, string, boolean), compound types (array, object), and special types (NULL, resource), with type determined dynamically at runtime."
  },
  {
    id: 6,
    category: "Basic",
    question: "Difference between == and ===",
    shortAnswer: "`==` sirf value compare karta hai (type ignore karke), jabki `===` value aur data type dono compare karta hai.",
    explanation: "`==` ko 'loose comparison' kehte hain — ye comparison se pehle type juggling/conversion karta hai, jisse kabhi-kabhi unexpected result aata hai. `===` ko 'strict comparison' kehte hain — ye tabhi true return karta hai jab dono value aur type match kare. Interview me ye ek bahut common question hai kyunki loose comparison se security aur logic bugs aa sakte hain.",
    example: "`0 == \"abc\"` PHP ke purane versions me kabhi true return kar sakta tha (type juggling ki wajah se), lekin `0 === \"abc\"` hamesha false hoga.",
    code: `<?php\nvar_dump(0 == "a");     // depends on PHP version\nvar_dump("1" == 1);     // true (loose)\nvar_dump("1" === 1);    // false (strict)\n?>`,
    output: "bool(false)\nbool(true)\nbool(false)",
    mistakes: "Password ya token comparison me `==` use karna dangerous ho sakta hai — hamesha `===` use karo jab type match bhi zaroori ho.",
    interviewDefinition: "The `==` operator performs loose comparison with type coercion, whereas `===` performs strict comparison, checking both value and data type equality."
  },
  {
    id: 7,
    category: "Basic",
    question: "What are constants?",
    shortAnswer: "Constants aise identifiers hain jinki value ek baar define hone ke baad change nahi ki ja sakti, `define()` ya `const` keyword se banaye jate hain.",
    explanation: "Variables ke opposite, constants ka value program ke run hone ke dauraan modify nahi kiya ja sakta. Constants case-sensitive hote hain by default aur inke naam ke aage `$` sign nahi lagta. `define()` function runtime par constant banata hai, jabki `const` keyword compile-time par (class ke andar bhi use hota hai) constant define karta hai.",
    example: "Ek application me `MAX_LOGIN_ATTEMPTS` ya `SITE_NAME` jaisi values constants ke roop me define ki jati hain kyunki ye change nahi honi chahiye.",
    code: `<?php\ndefine("SITE_NAME", "PHP Interview Master");\nconst MAX_ATTEMPTS = 5;\necho SITE_NAME . " allows " . MAX_ATTEMPTS . " attempts.";\n?>`,
    output: "PHP Interview Master allows 5 attempts.",
    mistakes: "Constant ko `$` sign ke saath access karne ki galti karna (`$SITE_NAME`) — constants ko directly naam se access kiya jata hai.",
    interviewDefinition: "A constant is an identifier for a fixed value that cannot be changed during script execution, defined using either the `define()` function or the `const` keyword."
  },
  {
    id: 8,
    category: "Basic",
    question: "What is an array?",
    shortAnswer: "Array ek data structure hai jo multiple values ko ek hi variable me store karta hai.",
    explanation: "PHP me array ordered map hota hai jo keys ko values se associate karta hai. Ye bahut flexible hote hain — ek hi array me alag-alag data types store kiye ja sakte hain. Arrays ko `array()` function ya short syntax `[]` se banaya ja sakta hai. Array functions jaise `count()`, `array_push()`, `array_merge()` inko manipulate karne ke liye use hote hain.",
    example: "Ek shopping list ko ek single array me store kiya ja sakta hai instead of alag-alag variables banane ke.",
    code: `<?php\n$fruits = ["Apple", "Banana", "Mango"];\necho count($fruits);\nprint_r($fruits);\n?>`,
    output: "3\nArray\n(\n    [0] => Apple\n    [1] => Banana\n    [2] => Mango\n)",
    mistakes: "Array index out of range access karna (jaise `$fruits[5]` jab sirf 3 elements hain) — ye 'Undefined array key' warning deta hai.",
    interviewDefinition: "An array is a composite data type in PHP that stores multiple values, either indexed numerically or by string keys, within a single variable."
  },
  {
    id: 9,
    category: "Basic",
    question: "Indexed vs associative array",
    shortAnswer: "Indexed array me keys numeric aur automatic hoti hain, associative array me keys custom (string ya defined) hoti hain.",
    explanation: "Indexed array default numeric index (0, 1, 2...) use karta hai jo automatically assign hota hai. Associative array me hum khud key define karte hain, jaise `\"name\" => \"Krishna\"`, jisse data ko meaningful naam ke saath access karna aasan ho jata hai. Dono ko `foreach` loop se easily iterate kiya ja sakta hai.",
    example: "Ek user ki details ko associative array me store karna zyada readable hota hai: `[\"name\" => \"Krishna\", \"role\" => \"Developer\"]`.",
    code: `<?php\n$indexed = ["PHP", "Laravel"];\n$assoc = ["name" => "Krishna", "role" => "Developer"];\necho $indexed[0] . " - " . $assoc["name"];\n?>`,
    output: "PHP - Krishna",
    mistakes: "Associative array me numeric-like string key use karke confuse ho jana (jaise `\"1\"` key), jo PHP kabhi-kabhi integer me convert kar deta hai.",
    interviewDefinition: "An indexed array uses sequential numeric keys assigned automatically, while an associative array uses custom, developer-defined keys to map to values."
  },
  {
    id: 10,
    category: "Basic",
    question: "What is a multidimensional array?",
    shortAnswer: "Multidimensional array ek array hota hai jiske andar aur bhi arrays hote hain — matlab 'array of arrays'.",
    explanation: "Jab data structure complex ho, jaise table ya grid jaisa data, tab multidimensional array useful hota hai. Ye 2D, 3D ya usse bhi zyada levels tak nested ho sakta hai, lekin practically 2D-3D tak hi common hai readability ke liye. Nested `foreach` loops se inhe traverse kiya jata hai.",
    example: "Ek students ki list jisme har student ka naam, marks, aur subjects ho, usko multidimensional array me store karna natural hota hai.",
    code: `<?php\n$students = [\n  ["name" => "Krishna", "marks" => 85],\n  ["name" => "Aman", "marks" => 90]\n];\nforeach ($students as $s) {\n  echo $s["name"] . ": " . $s["marks"] . "\\n";\n}\n?>`,
    output: "Krishna: 85\nAman: 90",
    mistakes: "Deeply nested arrays (4-5 levels) banana jo debug karna mushkil ho jata hai — better hota hai objects ya classes use karna complex data ke liye.",
    interviewDefinition: "A multidimensional array is an array that contains one or more nested arrays, commonly used to represent tabular or hierarchical data structures."
  },
  {
    id: 11,
    category: "Basic",
    question: "What is a function?",
    shortAnswer: "Function code ka ek reusable block hota hai jo ek specific task perform karta hai aur baar-baar call kiya ja sakta hai.",
    explanation: "Functions code duplication kam karte hain aur program ko modular banate hain. PHP me function `function` keyword se define hota hai. Ye parameters accept kar sakta hai aur `return` statement se value wapas bhej sakta hai. Built-in functions (jaise `strlen()`) ke alawa hum apne custom functions bhi bana sakte hain.",
    example: "Ek `calculateTax($amount)` function bana kar use puri application me kahin bhi call kiya ja sakta hai instead of tax calculation logic har jagah repeat karne ke.",
    code: `<?php\nfunction greet($name) {\n  return "Hello, " . $name . "!";\n}\necho greet("Krishna");\n?>`,
    output: "Hello, Krishna!",
    mistakes: "Function ke andar `echo` aur `return` ko confuse karna — `echo` sirf print karta hai, `return` value ko function ke bahar bhejta hai for further use.",
    interviewDefinition: "A function is a self-contained, reusable block of code designed to perform a specific task, which can accept parameters and optionally return a value."
  },
  {
    id: 12,
    category: "Basic",
    question: "Function parameters and return values",
    shortAnswer: "Parameters function ko input data dete hain, aur `return` statement function se output value bahar bhejta hai.",
    explanation: "PHP functions me default parameter values set kiye ja sakte hain, jisse function call ke time wo argument optional ho jata hai. PHP 7+ me type hinting bhi possible hai (jaise `function add(int $a, int $b): int`), jisse type-safety improve hoti hai. Ek function multiple values return karne ke liye array ya object bhi return kar sakta hai.",
    example: "Ek `calculateDiscount($price, $percent = 10)` function me `$percent` default 10 hai, agar call karte waqt na diya jaye.",
    code: `<?php\nfunction add(int $a, int $b = 5): int {\n  return $a + $b;\n}\necho add(10);      // uses default\necho add(10, 20);\n?>`,
    output: "15\n30",
    mistakes: "Return type declare karke bhi function ke andar galat type return karna, jo PHP strict_types on hone par TypeError deta hai.",
    interviewDefinition: "Function parameters define the inputs a function accepts (optionally with default values and type hints), while the return statement specifies the value passed back to the caller."
  },
  {
    id: 13,
    category: "Basic",
    question: "What is variable scope?",
    shortAnswer: "Variable scope define karta hai ki ek variable program ke kis part me accessible hai.",
    explanation: "PHP me mainly 3 scopes hote hain: local (function ke andar defined, sirf usi function me accessible), global (function ke bahar defined, poore script me accessible but function ke andar directly nahi), aur static (function call ke beech value retain karta hai). Scope samajhna important hai kyunki isse related bugs (jaise 'undefined variable') aate hain.",
    example: "Ek function ke andar declare kiya gaya `$counter` us function ke bahar accessible nahi hoga, jab tak use global ya return na kiya jaye.",
    code: `<?php\n$x = 10; // global\nfunction test() {\n  echo $x ?? "not accessible"; // local scope\n}\ntest();\n?>`,
    output: "not accessible",
    mistakes: "Beginners assume karte hain ki global variable function ke andar automatically accessible hoga — actually explicitly `global` keyword ya parameter pass karna padta hai.",
    interviewDefinition: "Variable scope refers to the context within a program where a variable is accessible, with PHP primarily supporting local, global, and static scopes."
  },
  {
    id: 14,
    category: "Basic",
    question: "Local vs global variables",
    shortAnswer: "Local variables sirf jis function ke andar declare hote hain wahin accessible hote hain, global variables poore script me available hote hain.",
    explanation: "Function ke andar global variable access karne ke liye `global` keyword use hota hai, ya `$GLOBALS` superglobal array se access kiya ja sakta hai. Best practice ye hai ki global variables ka use kam se kam kiya jaye kyunki ye code ko unpredictable bana sakte hain — instead parameters aur return values ka use behtar hota hai.",
    example: "`$GLOBALS['siteName']` se kisi function ke andar bhi global `$siteName` variable ko access kiya ja sakta hai.",
    code: `<?php\n$count = 100;\nfunction showCount() {\n  global $count;\n  echo $count;\n}\nshowCount();\n?>`,
    output: "100",
    mistakes: "Har jagah `global` keyword use karke variables ko globally accessible banana — ye maintainability aur testing dono ko kharab karta hai (tight coupling).",
    interviewDefinition: "A local variable exists only within the function where it is declared, whereas a global variable is accessible throughout the entire script and can be brought into function scope using the `global` keyword."
  },
  {
    id: 15,
    category: "Basic",
    question: "What is include?",
    shortAnswer: "`include` ek statement hai jo dusri PHP file ko current file me insert karta hai. Agar file na mile to sirf warning aati hai, script chalta rehta hai.",
    explanation: "`include` code reusability ke liye use hota hai — jaise header, footer, ya config files ko multiple pages me repeat karne ke bajaye ek jagah rakh kar include karna. Agar included file exist nahi karti, PHP ek E_WARNING deta hai lekin script execution rukta nahi hai, aage ka code chalta rehta hai.",
    example: "Website ke har page me common navigation bar dikhane ke liye `include(\"navbar.php\")` use kiya jata hai.",
    code: `<?php\ninclude "header.php";\necho "Page Content";\n?>`,
    output: "Header content followed by 'Page Content' (warning agar header.php missing ho)",
    mistakes: "Critical files (jaise database config) ke liye `include` use karna — agar file missing ho to script galat state me continue ho sakti hai bina fail hue.",
    interviewDefinition: "`include` is a PHP statement that inserts and evaluates the contents of another file, producing a warning (but not stopping execution) if the target file is not found."
  },
  {
    id: 16,
    category: "Basic",
    question: "What is require?",
    shortAnswer: "`require` bhi file include karta hai, lekin agar file na mile to ye fatal error deta hai aur script turant stop ho jata hai.",
    explanation: "`require` un cases me use hota hai jahan file ka hona critical hai program ke sahi chalne ke liye — jaise database connection file ya core configuration. Iska variant `require_once` file ko sirf ek hi baar include karta hai, chahe use kitni baar bhi call kiya jaye, jisse duplicate declaration errors avoid hote hain.",
    example: "`require_once(\"config.php\")` use karna best practice hai taaki database credentials wali file bina fail ho load na ho aur duplicate na ho.",
    code: `<?php\nrequire_once "config.php";\necho "Config loaded successfully";\n?>`,
    output: "Config loaded successfully (ya fatal error agar config.php missing ho)",
    mistakes: "`require` aur `require_once` ko interchangeably use karna, jisse same class/function redeclare hone par 'Cannot redeclare' fatal error aa sakta hai.",
    interviewDefinition: "`require` includes and evaluates a file, halting script execution with a fatal error if the file cannot be found, making it suitable for essential dependencies."
  },
  {
    id: 17,
    category: "Basic",
    question: "Difference between include and require",
    shortAnswer: "Dono file include karte hain, lekin `include` file na milne par sirf warning deta hai jabki `require` fatal error deta hai aur execution stop ho jata hai.",
    explanation: "Iska use case decide karta hai kaunsa use karna hai: agar included file optional hai (jaise ek extra widget ya banner), `include` use karo. Agar file application ke chalne ke liye zaroori hai (jaise database connection, autoloader), `require` use karo taaki galat state me application aage na badhe.",
    example: "Ek optional social-media-share widget ke liye `include`, lekin core `bootstrap.php` file ke liye `require` use karna sahi approach hai.",
    code: `<?php\ninclude "optional-widget.php"; // warning if missing\nrequire "core-config.php";     // fatal error if missing\n?>`,
    output: "Depends on whether files exist — demonstrates differing failure behavior",
    mistakes: "Performance-critical ya security-critical files ke liye `include` use karna, jisse missing file silently application ko broken state me chala sakta hai.",
    interviewDefinition: "Both `include` and `require` import external files, but they differ in error handling: `include` triggers a recoverable warning while `require` triggers a fatal error and halts script execution."
  },
  {
    id: 18,
    category: "Basic",
    question: "What is isset()?",
    shortAnswer: "`isset()` check karta hai ki koi variable define hai aur uski value NULL nahi hai.",
    explanation: "`isset()` bahut commonly use hota hai form data, session variables, ya array keys check karne ke liye taaki 'Undefined variable' warnings avoid ki ja sakein. Ye multiple variables ek saath bhi check kar sakta hai — sabhi true hone par hi true return karega. Agar variable exist karta hai lekin uski value NULL hai, to `isset()` false return karega.",
    example: "Form submission handle karte waqt `if (isset($_POST['email']))` likh kar ye ensure kiya jata hai ki field actually submit hui hai.",
    code: `<?php\n$name = "Krishna";\nvar_dump(isset($name));\nvar_dump(isset($age));\n?>`,
    output: "bool(true)\nbool(false)",
    mistakes: "`isset()` ko `array_key_exists()` samajh lena — agar key exist karti hai but value NULL hai, `isset()` false dega jabki `array_key_exists()` true dega.",
    interviewDefinition: "`isset()` is a language construct that checks whether a variable is declared and has a value other than NULL, commonly used to safely validate the existence of data."
  },
  {
    id: 19,
    category: "Basic",
    question: "What is empty()?",
    shortAnswer: "`empty()` check karta hai ki variable 'empty' consider hota hai ya nahi — jaise 0, \"\", NULL, false, ya undefined.",
    explanation: "`empty()` un values ko true consider karta hai jo 'falsy' hoti hain: empty string, 0, \"0\", NULL, false, aur empty array. Ye `isset()` se zyada strict validation ke liye use hota hai jab hume actual meaningful data check karna ho, na ki sirf variable ka existence.",
    example: "Ek form field validate karte waqt agar user ne sirf spaces ya empty string submit kiya ho, `empty()` use karke us case ko catch kiya ja sakta hai.",
    code: `<?php\n$val = "0";\nvar_dump(empty($val));\nvar_dump(isset($val));\n?>`,
    output: "bool(true)\nbool(true)",
    mistakes: "String `\"0\"` ko `empty()` se check karna aur assume karna ki ye valid non-empty input hai — PHP me `\"0\"` empty consider hota hai jo unexpected bugs de sakta hai.",
    interviewDefinition: "`empty()` is a language construct that determines whether a variable is considered empty, returning true for values like 0, an empty string, NULL, false, or an empty array."
  },
  {
    id: 20,
    category: "Basic",
    question: "What is unset()?",
    shortAnswer: "`unset()` ek variable ko destroy kar deta hai, uske baad wo variable memory me exist nahi karta.",
    explanation: "`unset()` variable ki value aur reference dono ko remove kar deta hai — uske baad agar us variable ko access kiya jaye to 'undefined variable' warning aayegi. Ye memory management aur array se specific keys remove karne ke liye kaafi useful hota hai, especially large datasets ke sath kaam karte waqt.",
    example: "Session logout ke time `unset($_SESSION['user'])` call karke user ki session data clear ki jati hai.",
    code: `<?php\n$data = ["a" => 1, "b" => 2];\nunset($data["a"]);\nprint_r($data);\n?>`,
    output: "Array\n(\n    [b] => 2\n)",
    mistakes: "`unset()` ko variable ki value ko `null` set karne jaisa samajhna — ye alag hai, `unset()` variable ko completely remove karta hai jabki `= null` sirf value change karta hai.",
    interviewDefinition: "`unset()` is a function that destroys a specified variable, removing it entirely from memory rather than simply clearing its value."
  },
  {
    id: 21,
    category: "Basic",
    question: "GET vs POST",
    shortAnswer: "GET data ko URL me visible parameters ke roop me bhejta hai, POST data ko request body me hidden tarike se bhejta hai.",
    explanation: "GET requests generally data retrieve karne ke liye use hote hain aur limited amount of data carry kar sakte hain (URL length limit ki wajah se) — ye bookmarkable aur cacheable hote hain. POST requests data submit/create/update karne ke liye use hote hain, larger data carry kar sakte hain, aur browser history/URL me visible nahi hote, isliye sensitive data (jaise passwords) ke liye zyada suitable hain.",
    example: "Search page par query GET se bhejna common hai (`?search=php`), jabki login form ka data POST se bhejna zaroori hai security ke liye.",
    code: `<?php\n// GET example: url?name=Krishna\necho $_GET['name'] ?? 'No GET data';\n// POST example: form submission\necho $_POST['name'] ?? 'No POST data';\n?>`,
    output: "Krishna (agar corresponding GET/POST parameter bheja gaya ho)",
    mistakes: "Sensitive information (jaise password) GET method se bhejna — ye URL, browser history, aur server logs me plainly visible ho jata hai.",
    interviewDefinition: "GET transmits data as visible URL parameters and is typically used for retrieving data, while POST sends data within the request body, making it suitable for submitting sensitive or larger data payloads."
  },
  {
    id: 22,
    category: "Basic",
    question: "What are PHP superglobals?",
    shortAnswer: "Superglobals built-in PHP arrays hain jo har scope me automatically available hote hain, bina global keyword use kiye.",
    explanation: "PHP me main superglobals hain: `$_GET`, `$_POST`, `$_SESSION`, `$_COOKIE`, `$_SERVER`, `$_FILES`, `$_ENV`, aur `$_REQUEST`. Ye normal scope rules follow nahi karte — function ke andar bhi bina `global` keyword ke directly accessible hote hain, jisse form data, server info, aur session handling aasan ho jati hai.",
    example: "`$_SERVER['HTTP_USER_AGENT']` se hum pata kar sakte hain ki request kis browser se aayi hai.",
    code: `<?php\nfunction showServerInfo() {\n  echo $_SERVER['SERVER_NAME'] ?? 'localhost';\n}\nshowServerInfo();\n?>`,
    output: "localhost (ya actual server domain)",
    mistakes: "Superglobals ka data directly bina sanitize kiye database query ya output me use karna, jo SQL injection ya XSS jaisi vulnerabilities ko invite karta hai.",
    interviewDefinition: "Superglobals are built-in PHP variables that are automatically accessible in all scopes throughout a script, without requiring the `global` keyword, and are used to handle request, session, and server data."
  },
  {
    id: 23,
    category: "Basic",
    question: "What is $_SESSION?",
    shortAnswer: "`$_SESSION` ek superglobal array hai jo server-side me user ka data multiple pages ke beech persist karne ke liye use hota hai.",
    explanation: "Sessions server par store hoti hain (default temporary files me) aur browser ko sirf ek unique session ID cookie ke roop me milta hai. Session use karne se pehle `session_start()` call karna zaroori hai. Ye login systems, shopping carts, aur user preferences track karne ke liye widely use hota hai kyunki HTTP stateless protocol hai aur bina session ke server ko yaad nahi rehta ki request kis user ki hai.",
    example: "Login karne ke baad `$_SESSION['user_id'] = $id;` set karke har page par user ko logged-in maintain kiya jata hai.",
    code: `<?php\nsession_start();\n$_SESSION['username'] = "Krishna";\necho $_SESSION['username'];\n?>`,
    output: "Krishna",
    mistakes: "Har PHP file ke top par `session_start()` call karna bhool jana — agar ye call nahi hua to `$_SESSION` array kaam nahi karega.",
    interviewDefinition: "`$_SESSION` is a superglobal array used to store user-specific data on the server across multiple page requests, enabling stateful features like authentication and shopping carts."
  },
  {
    id: 24,
    category: "Basic",
    question: "What is $_COOKIE?",
    shortAnswer: "`$_COOKIE` superglobal array hai jo browser me client-side store ki gayi small pieces of data ko read karne ke liye use hota hai.",
    explanation: "Cookies server se `setcookie()` function se set kiye jate hain aur browser me ek certain time tak store rehte hain (expiry set karne par). Har subsequent request ke saath ye cookies automatically server ko bhej diye jate hain. Sessions ke opposite, cookies client-side store hote hain, isliye inme sensitive data directly store karna risky hota hai.",
    example: "'Remember Me' feature me user ka login token cookie me store kiya jata hai taaki agli baar bina login kiye site access ho sake.",
    code: `<?php\nsetcookie("username", "Krishna", time() + 3600);\necho $_COOKIE['username'] ?? 'Cookie not set yet';\n?>`,
    output: "Cookie not set yet (first load), Krishna (subsequent loads)",
    mistakes: "Cookies me directly password ya sensitive data store karna without encryption — cookies client-side hote hain aur inhe easily inspect/modify kiya ja sakta hai.",
    interviewDefinition: "`$_COOKIE` is a superglobal array used to access data stored on the client's browser as cookies, commonly used for persisting small amounts of information like user preferences across sessions."
  },
  {
    id: 25,
    category: "Basic",
    question: "Basic PHP form handling",
    shortAnswer: "PHP form data ko `$_GET` ya `$_POST` superglobals se receive karta hai, jise validate/sanitize karke process kiya jata hai.",
    explanation: "Ek typical form handling flow me: HTML form ka `action` attribute PHP file ko point karta hai, `method` GET ya POST hota hai. PHP side par submit hue data ko superglobal se access kiya jata hai, phir `trim()`, `htmlspecialchars()` jaise functions se sanitize kiya jata hai security aur clean data ke liye, aur zaroorat ho to database me save kiya jata hai.",
    example: "Ek contact form me user naam aur message submit karta hai, PHP us data ko validate karke email bhejta hai ya database me save karta hai.",
    code: `<?php\nif ($_SERVER["REQUEST_METHOD"] == "POST") {\n  $name = htmlspecialchars(trim($_POST['name']));\n  echo "Thank you, $name!";\n}\n?>`,
    output: "Thank you, Krishna! (agar 'Krishna' naam se form submit hua ho)",
    mistakes: "User input ko directly bina sanitize/validate kiye database query ya HTML output me use karna, jo SQL injection aur XSS attacks ka rasta khol deta hai.",
    interviewDefinition: "Basic PHP form handling involves capturing submitted data through the `$_GET` or `$_POST` superglobals, validating and sanitizing it, and then processing it for storage or further use."
  }
];
