// questions-expert.js — Questions 76–100 (Expert)
const expertQuestions = [
  {
    id: 76,
    category: "Expert",
    question: "SOLID principles",
    shortAnswer: "SOLID 5 design principles ka acronym hai jo maintainable, scalable, aur flexible object-oriented code likhne me help karte hain.",
    explanation: "S — Single Responsibility (ek class ka sirf ek hi reason honi chahiye change hone ka), O — Open/Closed (extension ke liye open, modification ke liye closed), L — Liskov Substitution (child class parent ko replace kar sake bina behavior break kiye), I — Interface Segregation (chhote, specific interfaces bade general interfaces se behtar hote hain), D — Dependency Inversion (high-level modules low-level modules par directly depend na karein, dono abstractions par depend karein). Ye principles Laravel jaise frameworks ke design me bhi dikhte hain.",
    example: "Ek `OrderProcessor` class jo order calculate bhi kare, database bhi save kare, aur email bhi bheje — ye Single Responsibility violate karta hai; inhe alag classes me split karna chahiye.",
    code: `<?php\ninterface Logger { public function log(string $msg): void; }\nclass FileLogger implements Logger {\n  public function log(string $msg): void { echo "File: $msg"; }\n}\nclass OrderService {\n  public function __construct(private Logger $logger) {}\n  public function process() { $this->logger->log("Order processed"); }\n}\n(new OrderService(new FileLogger()))->process();\n?>`,
    output: "File: Order processed",
    mistakes: "SOLID principles ko rigid rules ki tarah follow karna har situation me, jisse over-engineering ho jati hai — chhoti simple applications me pragmatic balance rakhna zaroori hai.",
    interviewDefinition: "SOLID is an acronym for five object-oriented design principles—Single Responsibility, Open/Closed, Liskov Substitution, Interface Segregation, and Dependency Inversion—that promote maintainable and extensible software architecture."
  },
  {
    id: 77,
    category: "Expert",
    question: "Design patterns",
    shortAnswer: "Design patterns proven, reusable solutions hain common software design problems ke liye, jo code ko more maintainable aur communicable banate hain team ke beech.",
    explanation: "Patterns 3 broad categories me divide hote hain: Creational (objects create karne ke tarike, jaise Singleton, Factory), Structural (classes/objects ko compose karna, jaise Adapter, Decorator), aur Behavioral (objects ke beech communication, jaise Observer, Strategy). PHP frameworks (Laravel, Symfony) me ye patterns extensively use hote hain — jaise Laravel ka Service Container Dependency Injection pattern par based hai.",
    example: "Ek notification system jo email, SMS, ya push notification bhej sake, Strategy pattern se implement kiya ja sakta hai jisme algorithm (notification type) runtime par swap ho sake.",
    code: `<?php\ninterface Shape { public function area(): float; }\nclass Circle implements Shape {\n  public function __construct(private float $radius) {}\n  public function area(): float { return pi() * $this->radius ** 2; }\n}\nclass ShapeFactory {\n  public static function create(string $type, ...$args): Shape {\n    return match($type) {\n      'circle' => new Circle(...$args),\n    };\n  }\n}\necho ShapeFactory::create('circle', 5)->area();\n?>`,
    output: "78.539816339745",
    mistakes: "Design patterns ko forcibly har jagah use karna even simple problems ke liye — pattern tab use karna chahiye jab actual complexity ho jise wo pattern solve karta hai, na ki 'best practice dikhaane' ke liye.",
    interviewDefinition: "Design patterns are proven, reusable solutions to recurring software design problems, categorized into creational, structural, and behavioral patterns, and widely used within modern PHP frameworks."
  },
  {
    id: 78,
    category: "Expert",
    question: "Dependency Injection",
    shortAnswer: "Dependency Injection (DI) ek technique hai jisme class ki dependencies (jo classes usse zaroorat hain) usse khud create karne ke bajaye bahar se pass ki jati hain.",
    explanation: "DI class ko uski dependencies se 'decouple' karta hai, jisse testing (mock objects use karke) aur maintainability dono improve hote hain. Dependencies constructor (constructor injection), setter methods (setter injection), ya method parameters ke through inject ki ja sakti hain. Laravel jaisa framework 'Service Container' ke through automatically dependencies resolve aur inject karta hai (auto-wiring).",
    example: "Ek `OrderService` ko `PaymentGateway` interface constructor me inject karna, taaki testing ke waqt real gateway ki jagah ek fake/mock gateway pass kiya ja sake.",
    code: `<?php\nclass EmailService {\n  public function send($msg) { return "Email sent: $msg"; }\n}\nclass NotificationController {\n  public function __construct(private EmailService $emailService) {}\n  public function notify($msg) {\n    return $this->emailService->send($msg);\n  }\n}\n$controller = new NotificationController(new EmailService());\necho $controller->notify("Order confirmed");\n?>`,
    output: "Email sent: Order confirmed",
    mistakes: "Class ke andar `new` keyword se directly dependencies create karna (jaise `new PaymentGateway()` constructor ke andar) — isse class tightly coupled ho jati hai aur unit testing mushkil ho jati hai.",
    interviewDefinition: "Dependency Injection is a design technique where a class's required dependencies are supplied externally—typically via constructor parameters—rather than being instantiated internally, improving testability and decoupling."
  },
  {
    id: 79,
    category: "Expert",
    question: "Dependency Inversion",
    shortAnswer: "Dependency Inversion Principle (DIP) kehta hai ki high-level modules ko low-level modules par directly depend nahi karna chahiye — dono ko abstractions (interfaces) par depend karna chahiye.",
    explanation: "Ye SOLID ka 'D' hai. Iska matlab ye hai ki concrete classes ke bajaye code ko interfaces/abstract classes ke against likha jaye. Isse implementation change karna (jaise ek database driver se dusre me switch karna) bina high-level business logic ko touch kiye possible ho jata hai. DIP aur Dependency Injection saath me use hote hain, lekin DIP ek principle hai jabki DI uska implementation technique hai.",
    example: "Ek `OrderService` `PaymentGatewayInterface` par depend kare, na ki directly `StripeGateway` class par — taaki kal `PaypalGateway` switch karna aasan ho.",
    code: `<?php\ninterface PaymentGateway { public function charge(float $amount): bool; }\nclass StripeGateway implements PaymentGateway {\n  public function charge(float $amount): bool { return true; }\n}\nclass CheckoutService {\n  public function __construct(private PaymentGateway $gateway) {}\n  public function checkout(float $amount) {\n    return $this->gateway->charge($amount) ? "Payment successful" : "Payment failed";\n  }\n}\necho (new CheckoutService(new StripeGateway()))->checkout(500);\n?>`,
    output: "Payment successful",
    mistakes: "Interface banane ke bawajood bhi class ke andar concrete class ka type-hint use karna (jaise `StripeGateway $gateway` instead of `PaymentGateway $gateway`) — ye DIP ke fayde ko khatam kar deta hai.",
    interviewDefinition: "The Dependency Inversion Principle states that high-level modules should depend on abstractions rather than concrete implementations, decoupling business logic from specific low-level details."
  },
  {
    id: 80,
    category: "Expert",
    question: "Repository Pattern",
    shortAnswer: "Repository Pattern data access logic ko ek dedicated layer (repository) me abstract karta hai, jisse business logic ko database ke actual implementation details se decouple kiya ja sake.",
    explanation: "Repository ek interface ki tarah kaam karta hai jo data operations (jaise `find()`, `save()`, `delete()`) expose karta hai, bina caller ko batae ki data actually kahan se aa raha hai (MySQL, API, ya file). Ye testing ko aasan banata hai (fake repository use karke) aur agar data source change ho (jaise database se external API), business logic untouched rehta hai.",
    example: "Ek `UserRepository` interface `findById()`, `save()` methods define kare, aur `EloquentUserRepository` uska actual Laravel/Eloquent-based implementation ho.",
    code: `<?php\ninterface UserRepository { public function find(int $id): ?array; }\nclass InMemoryUserRepository implements UserRepository {\n  private array $users = [1 => ["id" => 1, "name" => "Krishna"]];\n  public function find(int $id): ?array {\n    return $this->users[$id] ?? null;\n  }\n}\n$repo = new InMemoryUserRepository();\nprint_r($repo->find(1));\n?>`,
    output: "Array\n(\n    [id] => 1\n    [name] => Krishna\n)",
    mistakes: "Repository ke andar business logic (jaise validation ya calculations) daal dena — repository ka sirf ek hi kaam hona chahiye: data ko fetch/persist karna, business rules service layer me honi chahiye.",
    interviewDefinition: "The Repository Pattern abstracts data access logic behind a dedicated interface, decoupling business logic from the specifics of the underlying data source and simplifying testing."
  },
  {
    id: 81,
    category: "Expert",
    question: "Service Layer",
    shortAnswer: "Service Layer ek architectural layer hai jo application ki business logic ko encapsulate karta hai, controllers aur data access layer ke beech ek clean separation banata hai.",
    explanation: "Bina service layer ke, controllers me business logic (calculations, validations, multiple repositories ka coordination) directly likhi jati hai, jo unhe 'fat controllers' bana deta hai — hard to test aur reuse karna. Service classes is logic ko encapsulate karti hain, jisse controllers sirf HTTP request/response handle karte hain aur actual 'kaam' service layer karta hai, jo multiple entry points (web, API, CLI) se reuse ho sakti hai.",
    example: "Ek `OrderController` seedha database queries likhne ke bajaye `OrderService::placeOrder()` call kare, jo internally validation, inventory check, aur payment processing coordinate kare.",
    code: `<?php\nclass OrderService {\n  public function placeOrder(array $items): string {\n    $total = array_sum(array_column($items, 'price'));\n    return "Order placed. Total: $total";\n  }\n}\n$service = new OrderService();\necho $service->placeOrder([["price" => 100], ["price" => 250]]);\n?>`,
    output: "Order placed. Total: 350",
    mistakes: "Controllers me hi directly database queries aur business rules likh dena, jisse code reuse na ho paye across different interfaces (web vs API) aur unit testing mushkil ho jaye.",
    interviewDefinition: "The Service Layer is an architectural layer that encapsulates application business logic separately from controllers and data access code, promoting reusability and testability across multiple entry points."
  },
  {
    id: 82,
    category: "Expert",
    question: "MVC architecture",
    shortAnswer: "MVC (Model-View-Controller) ek architectural pattern hai jo application ko teen interconnected parts me organize karta hai: data (Model), presentation (View), aur logic (Controller).",
    explanation: "Model data aur business rules represent karta hai (aksar database ke saath interact karta hai). View sirf presentation/UI handle karta hai — user ko kya dikhega. Controller in dono ke beech mediator ki tarah kaam karta hai — user input receive karta hai, Model se data manipulate karwata hai, aur appropriate View select karta hai response dene ke liye. Laravel is pattern ko strongly follow karta hai.",
    example: "Laravel me `routes/web.php` request ko `Controller` tak route karta hai, Controller `Model` (Eloquent) se data leta hai, aur `View` (Blade template) ko wo data pass karke render karta hai.",
    code: `<?php\nclass ProductModel {\n  public static function getAll(): array {\n    return [["name" => "Laptop"], ["name" => "Mouse"]];\n  }\n}\nclass ProductController {\n  public function index(): string {\n    $products = ProductModel::getAll();\n    return "Rendering view with " . count($products) . " products";\n  }\n}\necho (new ProductController())->index();\n?>`,
    output: "Rendering view with 2 products",
    mistakes: "View ke andar directly database queries likh dena (jaise Blade template ke andar Eloquent calls), jo MVC ki separation of concerns ko violate karta hai.",
    interviewDefinition: "MVC (Model-View-Controller) is an architectural pattern that separates an application into data management (Model), presentation (View), and request-handling logic (Controller), promoting organized and maintainable code."
  },
  {
    id: 83,
    category: "Expert",
    question: "Clean Architecture",
    shortAnswer: "Clean Architecture ek design approach hai jisme application ko concentric layers me organize kiya jata hai, jisme business logic (core) framework, database, aur UI details se completely independent rehta hai.",
    explanation: "Iska core idea 'Dependency Rule' hai — dependencies sirf inward point kar sakti hain, outer layers (frameworks, databases, UI) inner layers (business rules) par depend kar sakti hain, lekin ulta nahi. Isse core business logic ko test karna aasan ho jata hai bina database ya web framework ki zaroorat ke, aur framework change karna (jaise Laravel se dusre framework me migrate) bhi easier ho jata hai kyunki business rules framework se bandhe nahi hote.",
    example: "Ek payment processing use-case class ko directly test kiya ja sake bina actual database ya HTTP layer set up kiye, sirf interfaces ke mock implementations use karke.",
    code: `<?php\ninterface OrderRepositoryInterface { public function save(array $order): bool; }\nclass PlaceOrderUseCase {\n  public function __construct(private OrderRepositoryInterface $repo) {}\n  public function execute(array $orderData): string {\n    return $this->repo->save($orderData) ? "Order saved" : "Failed";\n  }\n}\nclass FakeRepo implements OrderRepositoryInterface {\n  public function save(array $order): bool { return true; }\n}\necho (new PlaceOrderUseCase(new FakeRepo()))->execute(["item" => "Laptop"]);\n?>`,
    output: "Order saved",
    mistakes: "Business logic (use cases) ke andar framework-specific classes (jaise Eloquent Model ya Laravel Request) directly use karna, jo core logic ko framework se tightly couple kar deta hai aur Clean Architecture ke fayde khatam kar deta hai.",
    interviewDefinition: "Clean Architecture organizes an application into concentric layers where core business logic remains independent of frameworks, databases, and UI, following a strict inward-pointing dependency rule."
  },
  {
    id: 84,
    category: "Expert",
    question: "PHP-FPM",
    shortAnswer: "PHP-FPM (FastCGI Process Manager) ek alternative PHP implementation hai jo high-load websites ke liye specifically design kiya gaya hai, worker processes ke through requests handle karte hue.",
    explanation: "PHP-FPM PHP processes ka ek pool maintain karta hai jo web server (Nginx, Apache) ke saath FastCGI protocol ke through communicate karta hai. Ye request-per-process model use karta hai aur dynamic/static/ondemand process management strategies support karta hai — jisse traffic ke hisaab se worker processes automatically scale ho sakte hain, resource utilization optimize karte hue.",
    example: "Nginx server khud PHP execute nahi kar sakta, isliye ye PHP-FPM ko request forward karta hai jo actual PHP code process karke response wapas Nginx ko deta hai.",
    code: `<?php\n// php-fpm pool config example (www.conf):\n// pm = dynamic\n// pm.max_children = 50\n// pm.start_servers = 5\necho "PHP-FPM manages a pool of PHP worker processes";\n?>`,
    output: "PHP-FPM manages a pool of PHP worker processes",
    mistakes: "`pm.max_children` ko server ki available memory ke hisaab se properly configure na karna — bahut zyada high set karne par server memory exhaust ho sakti hai, bahut kam par requests queue me atak sakti hain.",
    interviewDefinition: "PHP-FPM (FastCGI Process Manager) is an alternative PHP process manager that handles requests through a configurable pool of worker processes, commonly paired with Nginx for high-performance production deployments."
  },
  {
    id: 85,
    category: "Expert",
    question: "Apache vs Nginx",
    shortAnswer: "Apache traditional process/thread-based model use karta hai har request ke liye, jabki Nginx event-driven, asynchronous architecture use karta hai jo high concurrency ko efficiently handle karta hai.",
    explanation: "Apache `.htaccess` ke through per-directory configuration allow karta hai, jo flexibility deta hai lekin performance thoda affect kar sakta hai. Nginx generally static content serve karne me aur high number of concurrent connections handle karne me zyada efficient hai, isliye ye aksar reverse proxy ya load balancer ki tarah bhi use hota hai (PHP-FPM ke saath combine karke). Modern PHP deployments me Nginx + PHP-FPM combination bahut common hai.",
    example: "Bade traffic wali websites (jaise high-traffic APIs) generally Nginx prefer karti hain uski memory efficiency aur concurrent connection handling ki wajah se.",
    code: `<?php\n// Nginx config snippet (conceptual)\n// location ~ \\.php$ {\n//   fastcgi_pass unix:/var/run/php/php8.3-fpm.sock;\n// }\necho "Nginx forwards PHP requests to PHP-FPM via FastCGI";\n?>`,
    output: "Nginx forwards PHP requests to PHP-FPM via FastCGI",
    mistakes: "Nginx ko Apache ki tarah `.htaccess` support karne wala samajh lena — Nginx `.htaccess` files support hi nahi karta, saari configuration server block me hi centrally karni padti hai.",
    interviewDefinition: "Apache uses a traditional process/thread-per-connection model with flexible per-directory configuration, while Nginx employs an event-driven, asynchronous architecture optimized for high concurrency and static content delivery."
  },
  {
    id: 86,
    category: "Expert",
    question: "PHP request lifecycle",
    shortAnswer: "PHP request lifecycle un steps ka sequence hai jo tab hote hain jab browser se ek request server tak pahunchti hai aur response wapas bhejti hai.",
    explanation: "Typical flow: (1) Browser HTTP request bhejta hai, (2) Web server (Nginx/Apache) request receive karke PHP-FPM ko forward karta hai, (3) PHP engine script ko parse aur compile karta hai bytecode me (ya OPcache se cached bytecode use karta hai), (4) Bytecode Zend Engine dwara execute hota hai, (5) Output buffer me collect hota hai, (6) Response headers ke saath client ko wapas bheja jata hai, aur (7) request end hone par memory cleanup hoti hai. Frameworks (Laravel) is flow ke andar apna bootstrapping, routing, middleware, aur controller execution add karte hain.",
    example: "Laravel me request pehle `public/index.php` se enter karti hai, phir kernel, middleware, router, controller se hoti hui response generate karti hai, aur wapas browser tak jaati hai.",
    code: `<?php\necho "1. Request received\\n";\necho "2. Routing determined\\n";\necho "3. Controller executed\\n";\necho "4. Response sent\\n";\n?>`,
    output: "1. Request received\n2. Routing determined\n3. Controller executed\n4. Response sent",
    mistakes: "Framework ke bootstrapping overhead (jaise Laravel ki service providers loading) ko ignore karke assume karna ki har request 'lightweight' hai — bade applications me isse cold-start performance impact ho sakta hai.",
    interviewDefinition: "The PHP request lifecycle describes the sequence from a web server receiving an HTTP request, forwarding it to the PHP engine for parsing/execution, through to generating and returning the final response to the client."
  },
  {
    id: 87,
    category: "Expert",
    question: "Composer autoloading internals",
    shortAnswer: "Composer autoloading internally ek generated mapping (`vendor/composer/autoload_*.php` files) maintain karta hai jo class names ko unki actual file locations se link karta hai.",
    explanation: "Jab `composer install`/`dump-autoload` run hota hai, Composer PSR-4 mappings (`composer.json` me define ki gayi) scan karke ek classmap ya namespace-prefix-to-directory mapping generate karta hai. Runtime par, jab koi undefined class use hoti hai, PHP `spl_autoload_register()` ke through registered Composer ka autoload function trigger hota hai, jo mapping check karke correct file `require` karta hai.",
    example: "`composer dump-autoload -o` command ek optimized classmap generate karta hai jo production me thoda better performance deta hai (especially bade projects me) directory scanning ke bajaye.",
    code: `<?php\nrequire 'vendor/autoload.php';\n// Behind the scenes: spl_autoload_register maps App\\Models\\User\n// to app/Models/User.php based on composer.json's PSR-4 config\necho "Autoloader ready to resolve namespaced classes";\n?>`,
    output: "Autoloader ready to resolve namespaced classes",
    mistakes: "Naye classes add karne ke baad `composer dump-autoload` run karna bhool jana (jab classmap mode use ho raha ho), jisse 'Class not found' errors aa sakte hain even though file physically exist karti hai.",
    interviewDefinition: "Composer's autoloading internals rely on generated mapping files that associate namespaces or class names with their file paths, registered via `spl_autoload_register()` to resolve classes on demand at runtime."
  },
  {
    id: 88,
    category: "Expert",
    question: "PSR standards",
    shortAnswer: "PSR (PHP Standard Recommendations) ek series hai coding aur interoperability standards ki jo PHP-FIG (Framework Interop Group) dwara maintain ki jati hai, jisse different PHP projects/libraries ke beech consistency aur compatibility ensure hoti hai.",
    explanation: "Kuch important PSRs hain: PSR-1 (basic coding standard), PSR-4 (autoloading standard), PSR-7 (HTTP message interfaces), aur PSR-12 (extended coding style guide). In standards ko follow karne se different vendors ke packages ek dusre ke saath smoothly kaam kar paate hain, aur developers ek project se dusre me switch karne par familiar conventions expect kar sakte hain.",
    example: "Almost sabhi modern PHP packages (jaise Guzzle HTTP client) PSR-7 compliant HTTP message objects use karte hain, jisse ye kisi bhi PSR-7 compatible framework ke saath easily integrate ho jate hain.",
    code: `<?php\n// PSR-4 autoloading example structure:\n// namespace App\\Services; --> maps to app/Services/ directory\nnamespace App\\Services;\nclass MailService {\n  public function send() { return "Mail sent per PSR-4 structure"; }\n}\necho (new MailService())->send();\n?>`,
    output: "Mail sent per PSR-4 structure",
    mistakes: "PSR standards ko sirf 'coding style rules' samajh lena — kuch PSRs (jaise PSR-7, PSR-11) actual interfaces/contracts define karte hain jo interoperability ke liye critical hain, sirf style guide nahi.",
    interviewDefinition: "PSR (PHP Standard Recommendations) are a set of coding and interoperability standards maintained by PHP-FIG, covering areas such as coding style (PSR-12), autoloading (PSR-4), and HTTP message interfaces (PSR-7)."
  },
  {
    id: 89,
    category: "Expert",
    question: "PSR-4",
    shortAnswer: "PSR-4 ek autoloading standard hai jo define karta hai ki namespace structure kaise file/directory structure se map honi chahiye, taaki classes automatically load ho sakein.",
    explanation: "PSR-4 ke rules ke mutabik, ek fully-qualified class name ka namespace prefix ek 'base directory' se corresponds karta hai, aur remaining namespace path directly sub-directories/file naam se match karta hai. `composer.json` me `\"autoload\": {\"psr-4\": {\"App\\\\\": \"app/\"}}` jaisi entry se ye mapping define ki jati hai, jisse `App\\Models\\User` class `app/Models/User.php` file se automatically resolve ho jaati hai.",
    example: "Laravel ke `App\\Http\\Controllers\\UserController` class ko PSR-4 ke hisaab se `app/Http/Controllers/UserController.php` file me hona chahiye.",
    code: `<?php\n// composer.json\n// { "autoload": { "psr-4": { "App\\\\": "app/" } } }\n\nnamespace App\\Models;\nclass User {\n  public function greet() { return "Hi, I follow PSR-4"; }\n}\necho (new User())->greet();\n?>`,
    output: "Hi, I follow PSR-4",
    mistakes: "Namespace aur actual folder structure ke case ya naming me mismatch rakhna (jaise namespace `App\\models` lekin folder `Models`) — kuch operating systems (case-sensitive Linux) par ye 'Class not found' error deta hai jo Windows par nahi aata (case-insensitive), jisse deployment ke baad hi bug pata chalta hai.",
    interviewDefinition: "PSR-4 is an autoloading standard that specifies how fully-qualified class names map to file paths based on a defined namespace prefix and base directory, enabling automatic class resolution."
  },
  {
    id: 90,
    category: "Expert",
    question: "Middleware",
    shortAnswer: "Middleware code ka wo layer hai jo HTTP request aur response ke beech se guzarta hai, jisse cross-cutting concerns (jaise authentication, logging) request pahunchne se pehle ya response bhejne se pehle handle kiye ja sakte hain.",
    explanation: "Middleware ek 'pipeline' ki tarah kaam karta hai — request multiple middleware layers se guzarti hai (jaise CORS check, authentication check, rate limiting) is se pehle ki wo actual controller tak pahunche, aur response bhi wapas usi pipeline se guzar sakta hai reverse order me. Ye code ko controllers me repeat karne ke bajaye ek centralized, reusable jagah par rakhne deta hai.",
    example: "Laravel me `auth` middleware ensure karta hai ki koi bhi route jisme ye middleware attached hai, wo sirf logged-in users hi access kar sakein, warna redirect ho jaye login page par.",
    code: `<?php\nfunction authMiddleware($request, $next) {\n  if (!$request['isLoggedIn']) {\n    return "Redirect to login";\n  }\n  return $next($request);\n}\n$request = ['isLoggedIn' => true];\necho authMiddleware($request, function($req) {\n  return "Controller reached, welcome!";\n});\n?>`,
    output: "Controller reached, welcome!",
    mistakes: "Har route ke liye alag-alag jagah authentication logic duplicate likhna instead of ek centralized middleware use karne ke, jo maintenance nightmare bana deta hai jab logic change karni ho.",
    interviewDefinition: "Middleware is a layer of code that intercepts HTTP requests and responses to handle cross-cutting concerns like authentication, logging, or rate limiting, typically organized as a composable pipeline before requests reach the application's core logic."
  },
  {
    id: 91,
    category: "Expert",
    question: "Rate limiting",
    shortAnswer: "Rate limiting ek technique hai jo restrict karti hai ki ek client (user/IP) kitni requests ek certain time window ke andar API ko bhej sakta hai, abuse aur overload se bachne ke liye.",
    explanation: "Common algorithms hain: Fixed Window (jaise 100 requests per minute), Sliding Window (zyada accurate, rolling time window use karta hai), aur Token Bucket (tokens ek fixed rate se refill hote hain, har request ek token consume karti hai). Rate limiting exceed hone par server generally `429 Too Many Requests` status code return karta hai. Redis jaisi in-memory stores rate limiting counters store karne ke liye commonly use hoti hain unki speed ki wajah se.",
    example: "Ek public API `100 requests/hour` per API key allow kar sakta hai, us se zyada hone par `429` error ke saath 'Retry-After' header bhi bhej sakta hai.",
    code: `<?php\n$requestCount = 105; // example current count\n$limit = 100;\nif ($requestCount > $limit) {\n  http_response_code(429);\n  echo "Rate limit exceeded. Try again later.";\n} else {\n  echo "Request allowed";\n}\n?>`,
    output: "Rate limit exceeded. Try again later.",
    mistakes: "Rate limiting ko sirf application server memory me store karna (per-server counters) jab application multiple servers par load-balanced ho — isse actual limit inconsistent ho jata hai; centralized store (jaise Redis) zaroori hai distributed systems ke liye.",
    interviewDefinition: "Rate limiting restricts the number of requests a client can make within a defined time window to prevent abuse and overload, commonly implemented using fixed window, sliding window, or token bucket algorithms."
  },
  {
    id: 92,
    category: "Expert",
    question: "API versioning",
    shortAnswer: "API versioning ek strategy hai jo API ko evolve karne deti hai bina existing clients ko break kiye, generally URL, header, ya query parameter ke through version specify karke.",
    explanation: "Common approaches hain: URI versioning (`/api/v1/users`, `/api/v2/users`), header-based versioning (`Accept: application/vnd.api.v2+json`), aur query parameter versioning (`/api/users?version=2`). URI versioning sabse simple aur commonly used approach hai kyunki ye clearly visible aur cacheable hota hai. Versioning se breaking changes introduce karne par purane clients ko turant migrate karne ka pressure nahi padta.",
    example: "Ek mobile app jo `v1` API use kar rahi hai, wo tab tak kaam karti rahegi jab tak `v1` deprecated na ho jaye, chahe backend me `v2` naye features ke saath launch ho chuka ho.",
    code: `<?php\n$version = $_GET['version'] ?? 'v1';\nif ($version === 'v2') {\n  echo json_encode(["id" => 1, "name" => "Krishna", "role" => "Developer"]);\n} else {\n  echo json_encode(["id" => 1, "name" => "Krishna"]);\n}\n?>`,
    output: '{"id":1,"name":"Krishna"} (v1) ya {"id":1,"name":"Krishna","role":"Developer"} (v2)',
    mistakes: "Purani API versions ko bina kisi deprecation notice/timeline ke achanak hata dena, jisse existing clients ki application bina warning ke break ho jaati hai.",
    interviewDefinition: "API versioning is the practice of managing changes to an API—typically through URI paths, headers, or query parameters—so that existing clients continue functioning while new features are introduced."
  },
  {
    id: 93,
    category: "Expert",
    question: "Queue/background jobs",
    shortAnswer: "Queue/background jobs time-consuming tasks (jaise email bhejna, image processing) ko main request-response cycle se hata kar asynchronously ek background worker process me execute karte hain.",
    explanation: "Jab koi heavy task (jaise 1000 emails bhejna) directly request ke andar execute kiya jata hai, user ko response milne me der lagti hai. Queue system (jaise Laravel Queues with Redis/database driver) task ko ek queue me 'push' kar deta hai aur turant response return kar deta hai user ko, jabki ek separate worker process background me actual task perform karta hai. Ye user experience aur system scalability dono improve karta hai.",
    example: "Ek user registration hone par 'welcome email' turant bhejne ke bajaye queue me dala jata hai, taaki registration response fast rahe aur email background me chali jaye.",
    code: `<?php\n// Conceptual: dispatching a job to a queue\nfunction dispatchJob($jobName, $payload) {\n  echo "Job '$jobName' queued with payload: " . json_encode($payload);\n}\ndispatchJob("SendWelcomeEmail", ["user_id" => 101]);\n?>`,
    output: 'Job \'SendWelcomeEmail\' queued with payload: {"user_id":101}',
    mistakes: "Time-critical, heavy operations (jaise bulk report generation) ko synchronously request ke andar hi execute karte rehna, jisse request timeout ho sakti hai aur user experience kharab hota hai.",
    interviewDefinition: "Queues and background jobs offload time-consuming tasks from the main request-response cycle to asynchronous worker processes, improving application responsiveness and scalability."
  },
  {
    id: 94,
    category: "Expert",
    question: "Redis caching",
    shortAnswer: "Redis ek in-memory data store hai jo bahut fast read/write operations provide karta hai, isliye ye caching, session storage, aur queue management ke liye extensively use hota hai.",
    explanation: "Redis data ko RAM me store karta hai (disk ke bajaye), jisse traditional databases ke comparison me bahut fast access milta hai. Ye key-value pairs ke alawa complex data structures (lists, sets, hashes, sorted sets) bhi support karta hai. PHP applications me Redis extension ya `predis` library use karke Redis se connect kiya jata hai, aur expensive database queries ya computed results ko usme cache kiya jata hai TTL (time-to-live) ke saath.",
    example: "Ek 'trending products' list jo expensive aggregation query se banti hai, use Redis me 5 minutes ke TTL ke saath cache kiya ja sakta hai instead of har request par recalculate karne ke.",
    code: `<?php\n// Conceptual usage with Predis library\n// $redis = new Predis\\Client();\n// $redis->set('trending_products', json_encode($products), 'EX', 300);\n// $cached = $redis->get('trending_products');\necho "Redis stores frequently accessed data in-memory with an expiry (TTL)";\n?>`,
    output: "Redis stores frequently accessed data in-memory with an expiry (TTL)",
    mistakes: "Redis ko primary/persistent database ki tarah use karna without proper persistence configuration (RDB/AOF) — Redis primarily caching/ephemeral data ke liye optimized hai, critical persistent data ke liye nahi (jab tak specially configure na kiya jaye).",
    interviewDefinition: "Redis is an in-memory data store used for high-performance caching, session storage, and queue management, supporting key-value pairs as well as richer data structures with optional time-to-live expiration."
  },
  {
    id: 95,
    category: "Expert",
    question: "Database optimization",
    shortAnswer: "Database optimization techniques ka set hai jo query performance aur overall database efficiency improve karte hain — jaise proper indexing, query restructuring, aur normalization/denormalization decisions.",
    explanation: "Key techniques me shamil hain: appropriate indexes create karna frequently queried columns par, `EXPLAIN` command se query execution plans analyze karna, `SELECT *` ke bajaye sirf zaroori columns select karna, N+1 query problem avoid karna (eager loading se), aur bade tables ko partition/shard karna jab data volume bahut zyada ho jaye. Connection pooling aur read-replicas bhi high-traffic applications ke liye common optimization strategies hain.",
    example: "Ek slow-running dashboard query ko `EXPLAIN` se analyze karke pata chal sakta hai ki ek missing index full table scan force kar raha hai, jise fix karne se query time seconds se milliseconds tak aa sakta hai.",
    code: `<?php\n// SQL executed via PDO to analyze a query\n$stmt = $pdo->query("EXPLAIN SELECT * FROM orders WHERE customer_id = 5");\nprint_r($stmt->fetchAll());\n?>`,
    output: "Array of query execution plan details (table, type, possible_keys, rows scanned, etc.)",
    mistakes: "Sirf indexes add karke satisfy ho jana bina actual query patterns analyze kiye — galat column par index lagana, ya composite index ka galat column order rakhna, expected performance improvement nahi deta.",
    interviewDefinition: "Database optimization encompasses techniques such as proper indexing, query plan analysis, selective column retrieval, and avoiding inefficient query patterns to improve data retrieval performance and scalability."
  },
  {
    id: 96,
    category: "Expert",
    question: "N+1 query problem",
    shortAnswer: "N+1 query problem ek performance issue hai jisme ek query se N records fetch karne ke baad, har record ke related data ke liye alag-alag N additional queries chalayi jati hain — total N+1 queries.",
    explanation: "Ye tab hota hai jab ORM (jaise Eloquent) lazy loading use karta hai relationships ke liye — main query se parent records fetch hote hain, phir loop ke andar har parent ke liye related child records ke liye alag query trigger hoti hai. Solution hai 'eager loading' use karna (jaise Laravel me `with()` method), jisse related data ek hi additional query (ya JOIN) se saath me fetch ho jata hai.",
    example: "100 blog posts dikhane ke liye agar har post ke author ka naam alag query se fetch kiya jaye, to total 101 queries chalengi instead of 2 (ek posts ke liye, ek authors ke liye JOIN/eager-load se).",
    code: `<?php\n// Problematic (N+1):\n// foreach (Post::all() as $post) { echo $post->author->name; }\n\n// Optimized (Eager Loading):\n// foreach (Post::with('author')->get() as $post) { echo $post->author->name; }\necho "Eager loading reduces N+1 queries to a fixed, small number";\n?>`,
    output: "Eager loading reduces N+1 queries to a fixed, small number",
    mistakes: "ORM ke lazy loading default behavior par bharosa karke loops ke andar relationships access karte rehna bina eager loading consider kiye — ye large datasets ke saath application ko dramatically slow bana deta hai.",
    interviewDefinition: "The N+1 query problem occurs when fetching N records triggers an additional query for each record's related data, resulting in N+1 total queries; it is typically resolved through eager loading."
  },
  {
    id: 97,
    category: "Expert",
    question: "Horizontal scaling",
    shortAnswer: "Horizontal scaling (scaling out) ka matlab hai system ki capacity badhane ke liye zyada machines/servers add karna, ek single server ko powerful banane (vertical scaling) ke bajaye.",
    explanation: "Horizontal scaling me multiple identical servers traffic ko share karte hain, generally ek load balancer ke through. Ye better fault tolerance provide karta hai (ek server fail ho jaye to baaki chalte rehte hain) aur theoretically unlimited scaling allow karta hai, lekin isme additional complexity aati hai — jaise sessions ko centralized store (Redis) me rakhna zaroori ho jata hai kyunki alag-alag requests alag-alag servers par land kar sakti hain (stateless application design zaroori hai).",
    example: "Ek high-traffic e-commerce site peak sale season me demand handle karne ke liye 5 servers se 20 servers tak automatically scale ho sakti hai cloud auto-scaling groups ke through.",
    code: `<?php\n// Application must be stateless for horizontal scaling to work well\nsession_start(); // sessions must be stored centrally (e.g., Redis), not in local files\necho "Stateless design allows any server to handle any request";\n?>`,
    output: "Stateless design allows any server to handle any request",
    mistakes: "Session data ya file uploads ko individual server ki local disk par store karna jab application horizontally scaled ho — dusre server par land hone wali requests us data ko access nahi kar payengi, jisse inconsistent behavior aata hai.",
    interviewDefinition: "Horizontal scaling increases system capacity by adding more servers to distribute load, typically behind a load balancer, requiring stateless application design and centralized session/data storage for consistency."
  },
  {
    id: 98,
    category: "Expert",
    question: "Load balancing",
    shortAnswer: "Load balancing incoming network traffic ko multiple servers ke beech distribute karta hai, taaki koi ek single server overwhelmed na ho aur overall system availability/performance improve ho.",
    explanation: "Load balancers various algorithms use karte hain traffic distribute karne ke liye: Round Robin (requests sequentially har server ko), Least Connections (jis server par sabse kam active connections hain use bheja jaye), aur IP Hash (same client consistently same server par route ho, 'sticky sessions' ke liye). Load balancer health checks bhi karta hai — agar koi server unhealthy ho jaye, traffic automatically usse away route ho jata hai.",
    example: "Nginx ya AWS Elastic Load Balancer, multiple PHP-FPM servers ke beech incoming HTTP requests distribute kar sakta hai, ensuring koi single server overloaded na ho.",
    code: `<?php\n// Conceptual Nginx upstream config\n// upstream backend {\n//   server app1.internal;\n//   server app2.internal;\n// }\necho "Load balancer distributes requests across multiple backend servers";\n?>`,
    output: "Load balancer distributes requests across multiple backend servers",
    mistakes: "Load balancer ke peeche sticky sessions (IP hash) use karna assume karte hue ki ye 'session persistence' ka solution hai — actual best practice hai centralized session storage use karna, sticky sessions par depend karna scaling flexibility limit karta hai.",
    interviewDefinition: "Load balancing distributes incoming traffic across multiple servers using algorithms like round robin or least connections, improving availability, fault tolerance, and overall system performance."
  },
  {
    id: 99,
    category: "Expert",
    question: "Docker with PHP",
    shortAnswer: "Docker PHP applications ko containerize karne allow karta hai — application, uski dependencies, aur runtime environment ek portable, consistent 'container' me package ho jate hain.",
    explanation: "Ek typical PHP Docker setup me multiple services (containers) hote hain: ek PHP-FPM container application code run karne ke liye, ek Nginx container web server ke liye, aur ek MySQL/PostgreSQL container database ke liye — ye sab `docker-compose.yml` se orchestrate kiye jate hain. Docker ka fayda ye hai ki 'it works on my machine' problem solve ho jati hai, kyunki development, staging, aur production sabhi environments same container image use karte hain.",
    example: "Ek naye developer ko project setup karne ke liye sirf `docker-compose up` chalana padta hai, uske local machine par PHP version, extensions, ya database version manually install karne ki zaroorat nahi padti.",
    code: `<?php\n// Dockerfile snippet (conceptual)\n// FROM php:8.3-fpm\n// RUN docker-php-ext-install pdo pdo_mysql\n// COPY . /var/www/html\necho "Containerized PHP ensures consistent environments across dev, staging, and production";\n?>`,
    output: "Containerized PHP ensures consistent environments across dev, staging, and production",
    mistakes: "Production container image me development-only tools/configurations (jaise Xdebug enabled) chhod dena, jisse production performance significantly degrade ho sakti hai.",
    interviewDefinition: "Docker enables PHP applications to be containerized alongside their dependencies and runtime, ensuring consistent behavior across development, staging, and production environments, typically orchestrated via Docker Compose."
  },
  {
    id: 100,
    category: "Expert",
    question: "PHP performance optimization",
    shortAnswer: "PHP performance optimization me multiple techniques shamil hain — code-level, database-level, aur infrastructure-level — jo application ki speed aur resource efficiency improve karte hain.",
    explanation: "Key strategies hain: OPcache enable karna (bytecode caching), efficient database queries likhna (indexes, avoiding N+1), caching layers use karna (Redis/Memcached), unnecessary computations avoid karna loops ke andar, autoloading optimize karna (`composer dump-autoload -o`), aur profiling tools (jaise Xdebug profiler ya Blackfire) use karke actual bottlenecks identify karna — guesswork ki jagah data-driven optimization karna.",
    example: "Ek slow API endpoint ko profile karke pata chal sakta hai ki 80% time ek unoptimized database query me lag raha hai, jisse targeted optimization (index add karna) se dramatic improvement mil sakta hai.",
    code: `<?php\n$start = microtime(true);\n// Simulate some work\nfor ($i = 0; $i < 100000; $i++) { $x = $i * 2; }\n$end = microtime(true);\necho "Execution time: " . round(($end - $start) * 1000, 2) . " ms";\n?>`,
    output: "Execution time: 2.35 ms (approximate)",
    mistakes: "Bina profiling kiye 'random guesses' ke basis par optimization karna (jaise sirf caching add karte jaana), jisse actual bottleneck untouched reh jata hai aur time waste hota hai — hamesha measure-first approach follow karna chahiye.",
    interviewDefinition: "PHP performance optimization involves a combination of code-level efficiency, database query tuning, caching strategies, and profiling-driven analysis to systematically improve application speed and resource utilization."
  }
];
